### PR TITLE
Protect RRDP Endpoints

### PR DESCRIPTION
**Pull request by timbru**

### CODE REVIEW

**Comment by job** [comment]
wat is hier precies het voordeel van dit op deze manier een harde requirement maken? Nu we `same-origin` hebben zie ik zelf geen gevaar in GET parameters; parameters zouden gebruikt kunnen worden om verschillende RRDP servers/sessies van elkaar te onderscheiden.

Er zit niet wezelijk veel verschil tussen `https://example.net/rrdp/customer-A/notify.xml` en `https://example.net/rrdp/notify.xml?id=customer-A`

**Comment by tomhrr** [comment]
I agree with Job's comment.

**Comment by timbru** [comment]
@ties  can you comment as you suggested this in issue #22 ?

I think this is because get parameters could be used to bypass a CDN / proxy layer and generate direct hits on the back-end server. But I may have misunderstood.

**Comment by job** [comment]
Given that a repository operator _knows_ the pattern of endpoints (e.g. whether GET parameters are in use or not), the operator can of course load some kind of access control rules into its caching layer or frontend proxies to block trash requests.

IMHO the above doesn't transform into a `MUST NOT use GET parameters` - because... it depends! Since there is nothing inherently wrong with GET parameters in the general case, but in specific contexts (such as fronting RRDP endpoint with a CDN cache) - in such specific contexts, inherently there is a risk that folks purposefully try to trigger cache misses.

Perhaps the paragraph can be rewritten to draw attention to the concept of using an HTTP ACL of sorts to protect the infrastructure?

> Repository operators SHOULD use access control to protect the RRDP endpoints. E.g. if the repository operator knows HTTP GET parameters are not in use, then all requests containing GET parameters can be blocked.

something along those lines maybe helps?

**Pull request merged**
